/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-01-20 20:43:53 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class adminprofile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>Admin Profile</title>\r\n");
      out.write("<meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("<meta content=\"\" name=\"keywords\">\r\n");
      out.write("<meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("<!-- Favicons -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.png\"\r\n");
      out.write("\trel=\"icon\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/apple-touch-icon.png\"\r\n");
      out.write("\trel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("<!-- Google Fonts -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Bootstrap CSS File -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/bootstrap/css/bootstrap.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Libraries CSS Files -->\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/font-awesome/css/font-awesome.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/animate/animate.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/ionicons/css/ionicons.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/assets/owl.carousel.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/lightbox/css/lightbox.min.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("<!-- Main Stylesheet File -->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\"\r\n");
      out.write("\trel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("    Header\r\n");
      out.write("  ============================-->\r\n");
      out.write("\t<header id=\"header\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div id=\"logo\" class=\"pull-left\">\r\n");
      out.write("\t\t\t\t<h1>\r\n");
      out.write("\t\t\t\t\t<a href=\"#intro\" class=\"scrollto\">United Home Loans</a>\r\n");
      out.write("\t\t\t\t</h1>\r\n");
      out.write("\t\t\t\t<!-- Uncomment below if you prefer to use an image logo -->\r\n");
      out.write("\t\t\t\t<!-- <a href=\"#intro\"><img src=\"img/logo.png\" alt=\"\" title=\"\" /></a>-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<nav id=\"nav-menu-container\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav-menu\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"index2\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"calculators2\">Calculator</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"aboutus2\">About Us</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"faq2\">FAQ</a></li>\r\n");
      out.write("\t\t\t\t\t<li class=\"menu-active\"><a href=\"adminprofile\">Profile</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"logout\">Logout</a></li>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</nav>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\r\n");
      out.write("\t<!--==========================\r\n");
      out.write("    Intro Section\r\n");
      out.write("  ============================-->\r\n");
      out.write("\t<section id=\"intro2\">\r\n");
      out.write("\t\t<br> <br> <br> <br> <br>\r\n");
      out.write("\t\t<h2 class=\"text-center\">Welcome Admin!</h2>\r\n");
      out.write("\t\t<!-- <button type=\"button\" class=\"btn btn-success\">User Details</button> &nbsp; &nbsp;\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-warning\">View Documents</button> &nbsp; &nbsp;\r\n");
      out.write("            <button type=\"button\" class=\"btn btn-danger\">Loan Tracker</button>> &nbsp; &nbsp;\r\n");
      out.write("                <button type=\"button\" class=\"btn btn-info\">Account Details</button>&nbsp; &nbsp; -->\r\n");
      out.write("\r\n");
      out.write("\t\t<div align=\"center\">\r\n");
      out.write("\t\t\t<a href=\"listDetails\" class=\"btn btn-info\" role=\"button\">Customer\r\n");
      out.write("\t\t\t\tList</a> &nbsp; &nbsp; <a href=\"pending\" class=\"btn btn-success\"\r\n");
      out.write("\t\t\t\trole=\"button\">Pending Requests</a> &nbsp; &nbsp; <a href=\"approved\"\r\n");
      out.write("\t\t\t\tclass=\"btn btn-warning\" role=\"button\">Approved Requests</a> &nbsp;\r\n");
      out.write("\t\t\t&nbsp; <a href=\"rejected\" class=\"btn btn-danger\" role=\"button\">Rejected\r\n");
      out.write("\t\t\t\tRequests</a> &nbsp; &nbsp;\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t</section>\r\n");
      out.write("\t<!-- #intro -->\r\n");
      out.write("\r\n");
      out.write("\t<main id=\"main\"> <footer id=\"footer\">\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"footer-top\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 footer-info\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h3>United Home Loans</h3>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\t\t\t\t\t\t\tWe are here to guide you on <br>everything you need to know\r\n");
      out.write("\t\t\t\t\t\t\t<br>about availing a home loan.\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 footer-links\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4>Useful Links</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">Home</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">Calculators</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">About\r\n");
      out.write("\t\t\t\t\t\t\t\t\tUs</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">Terms\r\n");
      out.write("\t\t\t\t\t\t\t\t\tof service</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">Privacy\r\n");
      out.write("\t\t\t\t\t\t\t\t\tpolicy</a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</ul>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 footer-contact\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4>Contact Us</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\tTTC Electronic Zone, <br> Mahape Road, <br> Navi\r\n");
      out.write("\t\t\t\t\t\t\tMumbai, <br> Maharashtra 400710, <br>India <br> <br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<strong>Phone:</strong> 022 6795 4545<br> <strong>Email:</strong>\r\n");
      out.write("\t\t\t\t\t\t\tunitedhl@gmail.com<br>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</p>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<div class=\"social-links\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\"></i></a> <a\r\n");
      out.write("\t\t\t\t\t\t\t\thref=\"#\" class=\"google-plus\"><i class=\"fa fa-google-plus\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"linkedin\"><i class=\"fa fa-linkedin\"></i></a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t<div class=\"col-lg-3 col-md-6 footer-newsletter\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<h4>Our Newsletter</h4>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<p>Subscribe to our Newsletter for regular updates.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<form action=\"\" method=\"post\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"email\" name=\"email\"><input type=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\tvalue=\"Subscribe\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</form>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"copyright\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tDisclaimer - \"As regards deposit taking activity of the company, the\r\n");
      out.write("\t\t\t\tviewers may refer to the advertisement in the newspaper /\r\n");
      out.write("\t\t\t\tinformation furnished in the application form for soliciting public\r\n");
      out.write("\t\t\t\tdeposits; published on June 28, 2018 in the Free Press Journal and\r\n");
      out.write("\t\t\t\tin Navshakti, Mumbai, respectively. The Company is having a valid\r\n");
      out.write("\t\t\t\tCertificate of Registration dated 31/07/2001 issued by the National\r\n");
      out.write("\t\t\t\tHousing Bank under Section 29A of the National Housing Bank Act,\r\n");
      out.write("\t\t\t\t1987. However, the National Housing Bank does not accept any\r\n");
      out.write("\t\t\t\tresponsibility or guarantee about the present position as to the\r\n");
      out.write("\t\t\t\tfinancial soundness of the company or for the correctness of any of\r\n");
      out.write("\t\t\t\tthe statements or representations made or opinions expressed by the\r\n");
      out.write("\t\t\t\tcompany and for repayment of deposits / discharge of the liabilities\r\n");
      out.write("\t\t\t\tby the company.\" <br> <br> *The information mentioned\r\n");
      out.write("\t\t\t\therein is subject to change without prior notice. <br> Please\r\n");
      out.write("\t\t\t\tvisit your nearest United branch for detailed information on our\r\n");
      out.write("\t\t\t\tvarious products and changes, if any. Terms and conditions apply. <br>\r\n");
      out.write("\t\t\t\t<br> &copy; Copyright <strong>United Home Loans</strong>. All\r\n");
      out.write("\t\t\t\tRights Reserved\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"credits\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</footer><!-- #footer --> <a href=\"#\" class=\"back-to-top\"><i\r\n");
      out.write("\t\tclass=\"fa fa-chevron-up\"></i></a> <!-- Uncomment below i you want to use a preloader -->\r\n");
      out.write("\r\n");
      out.write("\t<!-- <div id=\"preloader\"></div> --> <a href=\"#\" class=\"back-to-top\"><i\r\n");
      out.write("\t\tclass=\"fa fa-chevron-up\"></i></a> <!-- Uncomment below i you want to use a preloader -->\r\n");
      out.write("\t<!-- <div id=\"preloader\"></div> --> <!-- JavaScript Libraries --> <script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/jquery/jquery-migrate.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/easing/easing.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/superfish/hoverIntent.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/superfish/superfish.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/wow/wow.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/counterup/counterup.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/isotope/isotope.pkgd.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/lightbox/js/lightbox.min.js\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/touchSwipe/jquery.touchSwipe.min.js\"></script>\r\n");
      out.write("\t<!-- Contact Form JavaScript File --> <script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/contactform/contactform.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Template Main Javascript File --> <script\r\n");
      out.write("\t\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
