/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.36
 * Generated at: 2019-01-20 16:38:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write(" \n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <title>United Home Loans</title>\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("  <meta content=\"\" name=\"keywords\">\n");
      out.write("  <meta content=\"\" name=\"description\">\n");
      out.write("\n");
      out.write("  <!-- Favicons -->\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/favicon.png\" rel=\"icon\">\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\n");
      out.write("\n");
      out.write("  <!-- Google Fonts -->\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Montserrat:300,400,500,700\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Bootstrap CSS File -->\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Libraries CSS Files -->\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/animate/animate.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/ionicons/css/ionicons.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/lightbox/css/lightbox.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("  <!-- Main Stylesheet File -->\n");
      out.write("  <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write(" \n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  <!--==========================\n");
      out.write("    Header\n");
      out.write("  ============================-->\n");
      out.write("  <header id=\"header\">\n");
      out.write("    <div class=\"container-fluid\">\n");
      out.write("\n");
      out.write("      <div id=\"logo\" class=\"pull-left\">\n");
      out.write("        <h1><a href=\"index.jsp\" class=\"scrollto\">United Home Loans</a></h1>\n");
      out.write("        <!-- Uncomment below if you prefer to use an image logo -->\n");
      out.write("<!--         <a href=\"#intro\"><img src=\"img/logo.png\" alt=\"\" title=\"\" /></a>\n");
      out.write(" -->      </div>\n");
      out.write("\n");
      out.write("      <nav id=\"nav-menu-container\">\n");
      out.write("        <ul class=\"nav-menu\">\n");
      out.write("         <li class=\"menu-active\"><a href=\"index2\">Home</a></li>\n");
      out.write("            <li><a href=\"calculators2\">Calculators</a></li>\n");
      out.write("            <li><a href=\"aboutus2\">About Us</a></li>\n");
      out.write("            <li><a href=\"faq2\">FAQ</a></li>\n");
      out.write("            <li><a href=\"adminprofile\">Profile</a></li>\n");
      out.write("            <li><a href=\"logout\">Logout</a></li>\n");
      out.write("          \n");
      out.write("        </ul>\n");
      out.write("      </nav><!-- #nav-menu-container -->\n");
      out.write("    </div>\n");
      out.write("  </header><!-- #header -->\n");
      out.write("\n");
      out.write("  <!--==========================\n");
      out.write("    Intro Section\n");
      out.write("  ============================-->\n");
      out.write("  <section id=\"intro\">\n");
      out.write("    <div class=\"intro-container\">\n");
      out.write("      <div id=\"introCarousel\" class=\"carousel  slide carousel-fade\" data-ride=\"carousel\">\n");
      out.write("\n");
      out.write("        <ol class=\"carousel-indicators\"></ol>\n");
      out.write("\n");
      out.write("        <div class=\"carousel-inner\" role=\"listbox\">\n");
      out.write("\n");
      out.write("          <div class=\"carousel-item active\">\n");
      out.write("            <div class=\"carousel-background\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/intro-carousel/1.jpg\" alt=\"\"></div>\n");
      out.write("            <div class=\"carousel-container\">\n");
      out.write("              <div class=\"carousel-content\">\n");
      out.write("                <h2>Move into your Dream Home</h2>\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>\n");
      out.write("                <a href=\"#featured-services\" class=\"btn-get-started scrollto\">Apply Now</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"carousel-item\">\n");
      out.write("            <div class=\"carousel-background\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/intro-carousel/2.jpg\" alt=\"\"></div>\n");
      out.write("            <div class=\"carousel-container\">\n");
      out.write("              <div class=\"carousel-content\">\n");
      out.write("                <h2>Turn your dreams into reality</h2>\n");
      out.write("                <p>Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut.</p>\n");
      out.write("                <a href=\"#featured-services\" class=\"btn-get-started scrollto\">Apply Now</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"carousel-item\">\n");
      out.write("            <div class=\"carousel-background\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/intro-carousel/3.jpg\" alt=\"\"></div>\n");
      out.write("            <div class=\"carousel-container\">\n");
      out.write("              <div class=\"carousel-content\">\n");
      out.write("                <h2>24/7 Customer Support</h2>\n");
      out.write("                <p>Beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt omnis iste natus error sit voluptatem accusantium.</p>\n");
      out.write("                <a href=\"#featured-services\" class=\"btn-get-started scrollto\">Apply Now</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"carousel-item\">\n");
      out.write("            <div class=\"carousel-background\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/intro-carousel/4.jpg\" alt=\"\"></div>\n");
      out.write("            <div class=\"carousel-container\">\n");
      out.write("              <div class=\"carousel-content\">\n");
      out.write("                <h2>Hassle-free Process</h2>\n");
      out.write("                <p>Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum.</p>\n");
      out.write("                <a href=\"#featured-services\" class=\"btn-get-started scrollto\">Apply Now</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"carousel-item\">\n");
      out.write("            <div class=\"carousel-background\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/intro-carousel/5.jpg\" alt=\"\"></div>\n");
      out.write("            <div class=\"carousel-container\">\n");
      out.write("              <div class=\"carousel-content\">\n");
      out.write("                <h2>100% Customer Satisfaction</h2>\n");
      out.write("                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>\n");
      out.write("                <a href=\"#featured-services\" class=\"btn-get-started scrollto\">Apply Now</a>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <a class=\"carousel-control-prev\" href=\"#introCarousel\" role=\"button\" data-slide=\"prev\">\n");
      out.write("          <span class=\"carousel-control-prev-icon ion-chevron-left\" aria-hidden=\"true\"></span>\n");
      out.write("          <span class=\"sr-only\">Previous</span>\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("        <a class=\"carousel-control-next\" href=\"#introCarousel\" role=\"button\" data-slide=\"next\">\n");
      out.write("          <span class=\"carousel-control-next-icon ion-chevron-right\" aria-hidden=\"true\"></span>\n");
      out.write("          <span class=\"sr-only\">Next</span>\n");
      out.write("        </a>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section><!-- #intro -->\n");
      out.write("\n");
      out.write("  <main id=\"main\">\n");
      out.write("\n");
      out.write("    <!--==========================\n");
      out.write("      Featured Services Section\n");
      out.write("    ============================-->\n");
      out.write("    <section id=\"featured-services\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 box\">\n");
      out.write("            <i class=\"ion-ios-bookmarks-outline\"></i>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Attractive Interest Rates</a></h4>\n");
      out.write("            <p class=\"description\">1Every day is a journey, and the journey itself is home.</p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 box box-bg\">\n");
      out.write("            <i class=\"ion-ios-stopwatch-outline\"></i>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Quick Approval</a></h4>\n");
      out.write("            <p class=\"description\">ex ea commodo consequat tarad limino ata</p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 box\">\n");
      out.write("            <i class=\"ion-ios-heart-outline\"></i>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Customer Satisfaction</a></h4>\n");
      out.write("            <p class=\"description\">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </section><!-- #featured-services -->\n");
      out.write("\n");
      out.write("    <!--==========================\n");
      out.write("      About Us Section\n");
      out.write("    ============================-->\n");
      out.write("    <section id=\"about\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <header class=\"section-header\">\n");
      out.write("          <h3>About Us</h3>\n");
      out.write("          <p>Transforming dreams to build a nation of proud homeowners. <br> For over three decades, United Home Loans has been providing easy access to <br> affordable Housing Finance to realise home-ownership aspirations of <br> millions of Lower and Middle income families in semi-urban and rural India.</p>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <header class=\"section-header\">\n");
      out.write("        <h3>Documents Required\n");
      out.write("            For Home Loans</h3>\n");
      out.write("        </header>\n");
      out.write("        <div class=\"row about-cols\">\n");
      out.write("          <div class=\"col-md-4 wow fadeInUp\">\n");
      out.write("            <div class=\"about-col\">\n");
      out.write("              <div class=\"img\">\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/about-mission.jpg\" alt=\"\" class=\"img-fluid\">\n");
      out.write("                <div class=\"icon\"><i class=\"ion-android-document\"></i></div>\n");
      out.write("              </div>\n");
      out.write("              <h2 class=\"title\"><a href=\"#\">KYC Documents</a></h2>\n");
      out.write("              <p>\n");
      out.write("                  Documents for proof of identity and address such as PAN card, Aadhaar card, Passport etc.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-md-4 wow fadeInUp\" data-wow-delay=\"0.1s\">\n");
      out.write("            <div class=\"about-col\">\n");
      out.write("              <div class=\"img\">\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/about-plan.jpg\" alt=\"\" class=\"img-fluid\">\n");
      out.write("                <div class=\"icon\"><i class=\"ion-card\"></i></div>\n");
      out.write("              </div>\n");
      out.write("              <h2 class=\"title\"><a href=\"#\">Income Documents</a></h2>\n");
      out.write("              <p>\n");
      out.write("                  Financial documents such as your salary slips, latest Form â 16, bank statements, etc.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-md-4 wow fadeInUp\" data-wow-delay=\"0.2s\">\n");
      out.write("            <div class=\"about-col\">\n");
      out.write("              <div class=\"img\">\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/about-vision.jpg\" alt=\"\" class=\"img-fluid\">\n");
      out.write("                <div class=\"icon\"><i class=\"ion-home\"></i></div>\n");
      out.write("              </div>\n");
      out.write("              <h2 class=\"title\"><a href=\"#\">Property Documents</a></h2>\n");
      out.write("              <p>\n");
      out.write("                  Documents such as Agreement to Sale, NOC, etc.\n");
      out.write("              </p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- #about -->\n");
      out.write("\n");
      out.write("    <!--==========================\n");
      out.write("      Services Section\n");
      out.write("    ============================-->\n");
      out.write("    <!-- <section id=\"services\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <header class=\"section-header wow fadeInUp\">\n");
      out.write("          <h3>Services</h3>\n");
      out.write("          <p>Laudem latine persequeris id sed, ex fabulas delectus quo. No vel partiendo abhorreant vituperatoribus, ad pro quaestio laboramus. Ei ubique vivendum pro. At ius nisl accusam lorenta zanos paradigno tridexa panatarel.</p>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-4 col-md-6 box wow bounceInUp\" data-wow-duration=\"1.4s\">\n");
      out.write("            <div class=\"icon\"><i class=\"ion-ios-analytics-outline\"></i></div>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Lorem Ipsum</a></h4>\n");
      out.write("            <p class=\"description\">Voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-4 col-md-6 box wow bounceInUp\" data-wow-duration=\"1.4s\">\n");
      out.write("            <div class=\"icon\"><i class=\"ion-ios-bookmarks-outline\"></i></div>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Dolor Sitema</a></h4>\n");
      out.write("            <p class=\"description\">Minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat tarad limino ata</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-4 col-md-6 box wow bounceInUp\" data-wow-duration=\"1.4s\">\n");
      out.write("            <div class=\"icon\"><i class=\"ion-ios-paper-outline\"></i></div>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Sed ut perspiciatis</a></h4>\n");
      out.write("            <p class=\"description\">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-4 col-md-6 box wow bounceInUp\" data-wow-delay=\"0.1s\" data-wow-duration=\"1.4s\">\n");
      out.write("            <div class=\"icon\"><i class=\"ion-ios-speedometer-outline\"></i></div>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Magni Dolores</a></h4>\n");
      out.write("            <p class=\"description\">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-4 col-md-6 box wow bounceInUp\" data-wow-delay=\"0.1s\" data-wow-duration=\"1.4s\">\n");
      out.write("            <div class=\"icon\"><i class=\"ion-ios-barcode-outline\"></i></div>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Nemo Enim</a></h4>\n");
      out.write("            <p class=\"description\">At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque</p>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-lg-4 col-md-6 box wow bounceInUp\" data-wow-delay=\"0.1s\" data-wow-duration=\"1.4s\">\n");
      out.write("            <div class=\"icon\"><i class=\"ion-ios-people-outline\"></i></div>\n");
      out.write("            <h4 class=\"title\"><a href=\"\">Eiusmod Tempor</a></h4>\n");
      out.write("            <p class=\"description\">Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi</p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("     -->\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <!--==========================\n");
      out.write("      Facts Section\n");
      out.write("    ============================-->\n");
      out.write("    <section id=\"facts\"  class=\"wow fadeIn\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <header class=\"section-header\">\n");
      out.write("          <h3>Facts</h3>\n");
      out.write("          <p>We let the numbers do the talking.</p>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <div class=\"row counters\">\n");
      out.write("\n");
      out.write("  \t\t\t\t<div class=\"col-lg-3 col-6 text-center\">\n");
      out.write("            <span data-toggle=\"counter-up\">274</span>\n");
      out.write("            <p>Clients</p>\n");
      out.write("  \t\t\t\t</div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-6 text-center\">\n");
      out.write("            <span data-toggle=\"counter-up\">421</span>\n");
      out.write("            <p>Projects</p>\n");
      out.write("  \t\t\t\t</div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-6 text-center\">\n");
      out.write("            <span data-toggle=\"counter-up\">1,364</span>\n");
      out.write("            <p>Hours Of Support</p>\n");
      out.write("  \t\t\t\t</div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-6 text-center\">\n");
      out.write("            <span data-toggle=\"counter-up\">18</span>\n");
      out.write("            <p>Hard Workers</p>\n");
      out.write("  \t\t\t\t</div>\n");
      out.write("\n");
      out.write("  \t\t\t</div>\n");
      out.write("\n");
      out.write("       \n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- #facts -->\n");
      out.write("\n");
      out.write("    \n");
      out.write("    <section id=\"testimonials\" class=\"section-bg wow fadeInUp\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <header class=\"section-header\">\n");
      out.write("          <h3>Testimonials</h3>\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <div class=\"owl-carousel testimonials-carousel\">\n");
      out.write("\n");
      out.write("          <div class=\"testimonial-item\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/testimonial-1.jpg\" class=\"testimonial-img\" alt=\"\">\n");
      out.write("            <h3>Saul Goodman</h3>\n");
      out.write("            <h4>Ceo &amp; Founder</h4>\n");
      out.write("            <p>\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-left.png\" class=\"quote-sign-left\" alt=\"\">\n");
      out.write("              I am really impressed by United's service as they always try and serve you better.\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-right.png\" class=\"quote-sign-right\" alt=\"\">\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"testimonial-item\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/testimonial-2.jpg\" class=\"testimonial-img\" alt=\"\">\n");
      out.write("            <h3>Sara Wilsson</h3>\n");
      out.write("            <h4>Designer</h4>\n");
      out.write("            <p>\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-left.png\" class=\"quote-sign-left\" alt=\"\">\n");
      out.write("              I got a loan in the shortest time period and that too without any difficulty. I take pride in owning a home today. \n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-right.png\" class=\"quote-sign-right\" alt=\"\">\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"testimonial-item\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/testimonial-3.jpg\" class=\"testimonial-img\" alt=\"\">\n");
      out.write("            <h3>Jena Karlis</h3>\n");
      out.write("            <h4>Store Owner</h4>\n");
      out.write("            <p>\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-left.png\" class=\"quote-sign-left\" alt=\"\">\n");
      out.write("              Other banks offer a very high interest rate, while United helped me to buy my dream home by providing me a low interest rate. \n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-right.png\" class=\"quote-sign-right\" alt=\"\">\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"testimonial-item\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/testimonial-4.jpg\" class=\"testimonial-img\" alt=\"\">\n");
      out.write("            <h3>Matt Brandon</h3>\n");
      out.write("            <h4>Freelancer</h4>\n");
      out.write("            <p>\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-left.png\" class=\"quote-sign-left\" alt=\"\">\n");
      out.write("              I was very upset with the tedious processes of other banks for a home loan. United sanctioned my loan without any hassles.\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-right.png\" class=\"quote-sign-right\" alt=\"\">\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"testimonial-item\">\n");
      out.write("            <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/testimonial-5.jpg\" class=\"testimonial-img\" alt=\"\">\n");
      out.write("            <h3>John Larson</h3>\n");
      out.write("            <h4>Entrepreneur</h4>\n");
      out.write("            <p>\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-left.png\" class=\"quote-sign-left\" alt=\"\">\n");
      out.write("              Other banks refused to give me a home loan because I work in an informal sector, United believed in my growth and supported me.\n");
      out.write("              <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/img/quote-sign-right.png\" class=\"quote-sign-right\" alt=\"\">\n");
      out.write("            </p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- #testimonials -->\n");
      out.write("\n");
      out.write("    \n");
      out.write("\n");
      out.write("    <!--==========================\n");
      out.write("      Contact Section\n");
      out.write("    ============================-->\n");
      out.write("    <section id=\"contact\" class=\"section-bg wow fadeInUp\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("\n");
      out.write("        <div class=\"section-header\">\n");
      out.write("          <h3>Contact Us</h3>\n");
      out.write("          \n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"row contact-info\">\n");
      out.write("\n");
      out.write("          <div class=\"col-md-4\">\n");
      out.write("            <div class=\"contact-address\">\n");
      out.write("              <i class=\"ion-ios-location-outline\"></i>\n");
      out.write("              <h3>Address</h3>\n");
      out.write("              <address>TTC Electronic Zone, Mahape Road, Navi Mumbai, Maharashtra 400710, India</address>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-md-4\">\n");
      out.write("            <div class=\"contact-phone\">\n");
      out.write("              <i class=\"ion-ios-telephone-outline\"></i>\n");
      out.write("              <h3>Phone Number</h3>\n");
      out.write("              <p><a href=\"tel:02267954545\"> 022 6795 4545</a></p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-md-4\">\n");
      out.write("            <div class=\"contact-email\">\n");
      out.write("              <i class=\"ion-ios-email-outline\"></i>\n");
      out.write("              <h3>Email</h3>\n");
      out.write("              <p><a href=\"mailto:unitedhl@gmail.com\">unitedhl@gmail.com</a></p>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"form\">\n");
      out.write("          <div id=\"sendmessage\">Your message has been sent. Thank you!</div>\n");
      out.write("          <div id=\"errormessage\"></div>\n");
      out.write("          <form action=\"\" method=\"post\" role=\"form\" class=\"contactForm\">\n");
      out.write("            <div class=\"form-row\">\n");
      out.write("              <div class=\"form-group col-md-6\">\n");
      out.write("                <input type=\"text\" name=\"name\" class=\"form-control\" id=\"name\" placeholder=\"Your Name\" data-rule=\"minlen:4\" data-msg=\"Please enter at least 4 chars\" />\n");
      out.write("                <div class=\"validation\"></div>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group col-md-6\">\n");
      out.write("                <input type=\"email\" class=\"form-control\" name=\"email\" id=\"email\" placeholder=\"Your Email\" data-rule=\"email\" data-msg=\"Please enter a valid email\" />\n");
      out.write("                <div class=\"validation\"></div>\n");
      out.write("              </div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <input type=\"text\" class=\"form-control\" name=\"subject\" id=\"subject\" placeholder=\"Subject\" data-rule=\"minlen:4\" data-msg=\"Please enter at least 8 chars of subject\" />\n");
      out.write("              <div class=\"validation\"></div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"form-group\">\n");
      out.write("              <textarea class=\"form-control\" name=\"message\" rows=\"5\" data-rule=\"required\" data-msg=\"Please write something for us\" placeholder=\"Message\"></textarea>\n");
      out.write("              <div class=\"validation\"></div>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"text-center\"><button type=\"submit\">Send Message</button></div>\n");
      out.write("          </form>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section><!-- #contact -->\n");
      out.write("\n");
      out.write("  </main>\n");
      out.write("\n");
      out.write("  <!--==========================\n");
      out.write("    Footer\n");
      out.write("  ============================-->\n");
      out.write("  <footer id=\"footer\">\n");
      out.write("    <div class=\"footer-top\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-md-6 footer-info\">\n");
      out.write("            <h3>United Home Loans</h3>\n");
      out.write("            <p>We are here to guide you on <br>everything you need to know <br>about availing a home loan.</p>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-md-6 footer-links\">\n");
      out.write("            <h4>Useful Links</h4>\n");
      out.write("            <ul>\n");
      out.write("              <li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">Home</a></li>\n");
      out.write("              <li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">Calculators</a></li>\n");
      out.write("              <li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">About Us</a></li>\n");
      out.write("              <li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">Terms of service</a></li>\n");
      out.write("              <li><i class=\"ion-ios-arrow-right\"></i> <a href=\"#\">Privacy policy</a></li>\n");
      out.write("            </ul>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-md-6 footer-contact\">\n");
      out.write("            <h4>Contact Us</h4>\n");
      out.write("            <p>\n");
      out.write("              TTC Electronic Zone, <br>\n");
      out.write("              Mahape Road, <br>\n");
      out.write("              Navi Mumbai, <br> Maharashtra 400710, <br>India <br> <br>\n");
      out.write("              <strong>Phone:</strong>  022 6795 4545<br>\n");
      out.write("              <strong>Email:</strong> unitedhl@gmail.com<br>\n");
      out.write("            </p>\n");
      out.write("\n");
      out.write("            <div class=\"social-links\">\n");
      out.write("              <a href=\"#\" class=\"twitter\"><i class=\"fa fa-twitter\"></i></a>\n");
      out.write("              <a href=\"#\" class=\"facebook\"><i class=\"fa fa-facebook\"></i></a>\n");
      out.write("              <a href=\"#\" class=\"instagram\"><i class=\"fa fa-instagram\"></i></a>\n");
      out.write("              <a href=\"#\" class=\"google-plus\"><i class=\"fa fa-google-plus\"></i></a>\n");
      out.write("              <a href=\"#\" class=\"linkedin\"><i class=\"fa fa-linkedin\"></i></a>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("          <div class=\"col-lg-3 col-md-6 footer-newsletter\">\n");
      out.write("            <h4>Our Newsletter</h4>\n");
      out.write("            <p>Subscribe to our Newsletter for regular updates.</p>\n");
      out.write("            <form action=\"\" method=\"post\">\n");
      out.write("              <input type=\"email\" name=\"email\"><input type=\"submit\"  value=\"Subscribe\">\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"container\">\n");
      out.write("      <div class=\"copyright\">\n");
      out.write("          Disclaimer - \"As regards deposit taking activity of the company, the viewers may refer to the advertisement in the newspaper / information furnished in the application form for soliciting public deposits; published on June 28, 2018 in the Free Press Journal and in Navshakti, Mumbai, respectively. The Company is having a valid Certificate of Registration dated 31/07/2001 issued by the National Housing Bank under Section 29A of the National Housing Bank Act, 1987. However, the National Housing Bank does not accept any responsibility or guarantee about the present position as to the financial soundness of the company or for the correctness of any of the statements or representations made or opinions expressed by the company and for repayment of deposits / discharge of the liabilities by the company.\"\n");
      out.write("          <br> <br>\n");
      out.write("          *The information mentioned herein is subject to change without prior notice. <br> Please visit your nearest United branch for detailed information on our various products and changes, if any. Terms and conditions apply. <br> <br>\n");
      out.write("        &copy; Copyright <strong>United Home Loans</strong>. All Rights Reserved\n");
      out.write("      </div>\n");
      out.write("      <div class=\"credits\">\n");
      out.write("       \n");
      out.write("      \n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </footer><!-- #footer -->\n");
      out.write("\n");
      out.write("  <a href=\"#\" class=\"back-to-top\"><i class=\"fa fa-chevron-up\"></i></a>\n");
      out.write("  <!-- Uncomment below i you want to use a preloader -->\n");
      out.write("  <!-- <div id=\"preloader\"></div> -->\n");
      out.write("\n");
      out.write("  <!-- JavaScript Libraries -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/jquery/jquery.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/jquery/jquery-migrate.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/easing/easing.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/superfish/hoverIntent.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/superfish/superfish.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/wow/wow.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/waypoints/waypoints.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/counterup/counterup.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/owlcarousel/owl.carousel.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/isotope/isotope.pkgd.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/lightbox/js/lightbox.min.js\"></script>\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/lib/touchSwipe/jquery.touchSwipe.min.js\"></script>\n");
      out.write("  <!-- Contact Form JavaScript File -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/contactform/contactform.js\"></script>\n");
      out.write("\n");
      out.write("  <!-- Template Main Javascript File -->\n");
      out.write("  <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/main.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
